# Generated by Django 4.2 on 2025-07-18 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataLatih',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Bisa', 'Bisa'), ('Tidak Bisa', 'Tidak Bisa')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DataUji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('hasil_prediksi', models.CharField(blank=True, max_length=100, null=True)),
                ('akurasi', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('alasan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PilihanKriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.IntegerField()),
                ('label', models.CharField(max_length=100)),
                ('kriteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilihan', to='prediksi.kriteria')),
            ],
        ),
        migrations.CreateModel(
            name='NilaiKriteriaUji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_uji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai_kriteria', to='prediksi.datauji')),
                ('kriteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prediksi.kriteria')),
                ('pilihan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prediksi.pilihankriteria')),
            ],
        ),
        migrations.CreateModel(
            name='NilaiKriteriaLatih',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_latih', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai_kriteria', to='prediksi.datalatih')),
                ('kriteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prediksi.kriteria')),
                ('pilihan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prediksi.pilihankriteria')),
            ],
        ),
    ]
