# Generated by Django 4.2 on 2025-06-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataLatih',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('hari', models.IntegerField(choices=[(1, 'Senin'), (2, 'Selasa'), (3, 'Rabu'), (4, 'Kamis'), (5, 'Jumat'), (6, 'Sabtu'), (7, 'Minggu')])),
                ('waktu', models.IntegerField(choices=[(1, 'Pagi'), (2, 'Siang'), (3, 'Sore')])),
                ('durasi', models.IntegerField()),
                ('paket', models.IntegerField()),
                ('umur', models.IntegerField()),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=10)),
                ('pekerjaan', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Bisa', 'Bisa'), ('Tidak Bisa', 'Tidak Bisa')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RiwayatPrediksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu', models.DateTimeField(auto_now_add=True)),
                ('hari', models.IntegerField()),
                ('waktu_kursus', models.IntegerField()),
                ('durasi', models.IntegerField()),
                ('paket', models.IntegerField()),
                ('umur', models.IntegerField()),
                ('jenis_kelamin', models.CharField(max_length=10)),
                ('pekerjaan', models.CharField(max_length=50)),
                ('hasil', models.CharField(max_length=20)),
            ],
        ),
    ]
