# Generated by Django 4.2 on 2025-07-18 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prediksi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datauji',
            name='akurasi',
        ),
        migrations.RemoveField(
            model_name='datauji',
            name='alasan',
        ),
        migrations.RemoveField(
            model_name='datauji',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='datauji',
            name='precision',
        ),
        migrations.RemoveField(
            model_name='datauji',
            name='recall',
        ),
    ]
