# Generated by Django 4.2 on 2025-07-19 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prediksi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datauji',
            name='akurasi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datauji',
            name='alasan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datauji',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datauji',
            name='precision',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datauji',
            name='recall',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
