# Generated by Django 4.2 on 2025-06-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediksi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('hari', models.IntegerField(choices=[(1, 'Senin'), (2, 'Selasa'), (3, 'Rabu'), (4, 'Kamis'), (5, 'Jumat'), (6, 'Sabtu')])),
                ('waktu', models.IntegerField(choices=[(1, 'Pagi'), (2, 'Siang'), (3, 'Sore')])),
                ('durasi', models.IntegerField()),
                ('paket', models.IntegerField(choices=[(0, 'Harian + SIM'), (1, 'Harian Tanpa SIM'), (2, 'Mingguan + SIM'), (3, 'Mingguan Tanpa SIM')])),
                ('hasil_prediksi', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='RiwayatPrediksi',
        ),
        migrations.RemoveField(
            model_name='datalatih',
            name='jenis_kelamin',
        ),
        migrations.RemoveField(
            model_name='datalatih',
            name='pekerjaan',
        ),
        migrations.RemoveField(
            model_name='datalatih',
            name='umur',
        ),
        migrations.AlterField(
            model_name='datalatih',
            name='hari',
            field=models.IntegerField(choices=[(1, 'Senin'), (2, 'Selasa'), (3, 'Rabu'), (4, 'Kamis'), (5, 'Jumat'), (6, 'Sabtu')]),
        ),
        migrations.AlterField(
            model_name='datalatih',
            name='paket',
            field=models.IntegerField(choices=[(0, 'Harian + SIM'), (1, 'Harian Tanpa SIM'), (2, 'Mingguan + SIM'), (3, 'Mingguan Tanpa SIM')]),
        ),
    ]
